---
title: "DO_bioavail"
output: html_document
date: "2024-06-10"
---

```{r}
library(tidyverse)
library(here)
library(readxl)
library(ggplot2)
library(RColorBrewer)
```
Load data:
```{r}
DO <- read.csv(here("data/DO_data.csv"))
```
Configure data
```{r}
short_DO <- DO %>%
  filter(str_detect(sampleID, "^DIT_06")) %>%
  group_by(shortID,day) %>%
  pivot_longer(read1:read5) %>%
  unique()

short_DO$shortID <- factor(short_DO$shortID, levels = c('FC1','FL1','BC1','BL1','SC1','SL1'))



short_DO <- DO %>%
  group_by(shortID,day) %>%
  pivot_longer(read1:read5) %>%
  reframe(mean = mean(value,na.rm = T),
            sd = sd(value, na.rm=T),
            shortID = shortID,
            sampleID = sampleID) %>%
  unique() %>%
  filter(str_detect(sampleID, "^DIT_06"))

short_DO$shortID <- factor(short_DO$shortID, levels = c('FC1','FL1','BC1','BL1','SC1','SL1'))
```
Graph averaging all available samples each day:
```{r}
short_DO %>%
  ggplot(aes(x = day, y = mean, color = shortID)) +
  geom_point() +
  theme_bw() +
  theme(legend.position = "bottom", legend.box = "horizontal", legend.title = element_blank()) +
  xlab("Day") +
  ylab("DO (ppm)") +
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd),width=0.2) +
  geom_line() +
  scale_color_brewer(palette="Dark2")
```
Graph only looking at the day 6 samples:
```{r}
fit1 <- lm(value ~ day, data = short_DO%>%filter(shortID=="BC1")) 

short_DO %>%
  filter(day != 2 & shortID == "BC1") %>% #remove filter for BC1, day 2 removed becayse the reading wasn't 24 hrs from the first
  ggplot(aes(x = day, y = value)) +
  geom_point() +
  theme_bw() +
  #facet_wrap(vars(shortID)) +
  theme(legend.position = "bottom", legend.box = "horizontal", legend.title = element_blank()) +
  xlab("Day") +
  ylab("DO (ppm)") +
  #scale_color_brewer(palette="Dark2") +
  geom_smooth(method='lm', formula= y~x) +
  geom_label(aes(x = 1, y = 6.5), hjust = 0, 
             label = paste("Adj R2 = ",signif(summary(fit1)$adj.r.squared, 5),
                                               "\nIntercept =",signif(fit1$coef[[1]],5 ),
                                               " \nSlope =",signif(fit1$coef[[2]], 5)))
```


