---
title: "workspace"
output: html_document
date: "2024-08-23"
---

Load Packages
```{r}
library(tidyverse)
library(here)
library(ggplot2)
```

Establish file path
```{r}
here::i_am("DIC_Raw_Data_Digestion/DIC_Raw_Data_Digestion.Rmd")
```

Pre-recs: Find the dslope, dintercept, and dtime necessary for the drift correction
```{r}
#create functions for the intercept, slope, and rsquared values
intercept <- function(x, y) coef(lm(y ~ x))[[1]]
slope <- function(x, y) coef(lm(y ~ x))[[2]]
rsquared <- function(x, y, slope, intercept) {
  # Calculate predicted y values based on x, slope and intercept
  y_pred <- slope * x + intercept
  # Calculate residuals
  residuals <- y - y_pred
  # Calculate total sum of squares
  total_sum_of_squares <- sum((y - mean(y))^2)
  # Calculate residual sum of squares
  residual_sum_of_squares <- sum(residuals^2)
  # Calculate R-squared
  r2 <- 1 - (residual_sum_of_squares / total_sum_of_squares)
  return(r2)
}
```

load the data
```{r}
dic_raw_0 <- read.csv2(here("DIC_Raw_Data_Digestion/Data/060324_EBSD_DIT_Day0_DIC.csv"), check.names = F)
dic_raw_0 <- dic_raw_0[,1:17]
dic_raw_0$`Start Time` <- as.POSIXct(dic_raw_0$`Start Time`, format="%m/%d/%y %H:%M:%S")
dic_raw_0 <- dic_raw_0 %>%
  filter(`Start Time` < "2024-06-03 14:51:44" | `Start Time` > "2024-06-03 15:32:32") # need to filter out the mid-run CRMs so the function will run IN PROGRESS, RILEY QUESTION

dic_raw_1 <- read.csv2(here("DIC_Raw_Data_Digestion/Data/060424_EBSD_DIT_Day1_DIC.csv"),check.names = F)

dic_raw_3 <- read.csv2(here("DIC_Raw_Data_Digestion/Data/060624_EBSD_DIT_Day3_DIC.csv"),check.names = F)

dic_raw_7 <- read.csv2(here("DIC_Raw_Data_Digestion/Data/061024_EBSD_DIT_Day7_DIC.csv"),check.names = F)
dic_raw_7 <- dic_raw_7[,1:17]
dic_raw_7$`Start Time` <- as.POSIXct(dic_raw_7$`Start Time`, format="%m/%d/%y %H:%M:%S")
dic_raw_7 <- dic_raw_7 %>%
  filter(`Start Time` > as.POSIXct("2024-06-10 10:26:59", format="%Y-%m-%d %H:%M:%S")) #run was stopped to create a fresh standard, this code filters out the old standard

dic_raw_10 <- read.csv2(here("DIC_Raw_Data_Digestion/Data/061324_EBSD_DIT_Day10_DIC.csv"),check.names = F)

dic_raw_14 <- read.csv2(here("DIC_Raw_Data_Digestion/Data/061724_EBSD_DIT_Day14_DIC.csv"),check.names = F)
dic_raw_14 <- dic_raw_14[,1:17]
dic_raw_14 <- dic_raw_14 %>%
  mutate(`Sample Name` = if_else(`Sample Name` == "", "CRM-15%",`Sample Name`)) # mutate the name column so that blank cells are filled with CRM-15% so the function will run

```
Get the drift correction parameters!

Create function specifically for our use:
```{r}

ditDigest <- function (dic_raw, batches = T, crm_percent = 5, roomtemp = 22) {

crm_dic <- 2024*crm_percent/100
crm_salinity <- 33.30*crm_percent/100
  
#select the rows we're interested in
dic_raw <- dic_raw[,1:17]
#filter for the valid runs
dic_raw <- dic_raw %>%
  filter(Status == "Valid")
#change the format of the time stamp to separate out the date and time
dic_raw$Time <- format(as.POSIXct(dic_raw$"Start Time", format="%m/%d/%y %H:%M:%S"),"%H:%M:%S")
dic_raw$Date <- format(as.POSIXct(dic_raw$"Start Time",format="%m/%d/%y %H:%M:%S"),"%m-%d-%y")
dic_raw$`Start Time` <- as.POSIXct(dic_raw$`Start Time`, format="%m/%d/%y %H:%M:%S")

#filter the sample for CRM runs (REQUIRES THAT ONLY CRM SAMPLES START WITH A C) and select the columns we'll be working with
dic_crm <- dic_raw %>%
  filter(str_detect(`Sample Name`, "^C") & !str_detect(`Sample Name`, "junk")) %>%
  select("Sample Name","Area (net avg)","Start Time","Sample # In Batch")

 if (batches == F){
#we need to do some extra work to get only the CRM timestamps we care about by selecting the single runs separately, then joining the pre and post crm dataframes.

dic_post_crm <- dic_raw %>%
  filter(str_detect(`Sample Name`, "^C") & !str_detect(`Sample Name`, "junk")) %>%
  select("Sample Name","Area (net avg)","Start Time","Sample # In Batch") 

dic_post_crm <- dic_post_crm %>%
  filter(dic_post_crm$`Sample # In Batch` == "Single")

#run this step to get every third time stamp for batch runs of CRMs
dic_pre_crm <- dic_raw %>%
  filter(str_detect(`Sample Name`, "^C") & !str_detect(`Sample Name`, "junk"))
dic_pre_crm <- filter(dic_pre_crm[1:18,], row_number() %% 3==1) %>%
  select("Sample Name","Area (net avg)","Start Time","Sample # In Batch")

#we now need to join the pre- and post- crm dataframes into one, and select the columns we care about
dic_crm <- rbind(dic_pre_crm, dic_post_crm) %>%
  select("Sample Name","Area (net avg)","Start Time")
 }

else {
#run this step to get every third time stamp for batch runs of CRMs. 
dic_crm <- dic_raw %>%
  filter(str_detect(`Sample Name`, "^C") & !str_detect(`Sample Name`, "junk"))
dic_crm <- filter(dic_crm[1:27,], row_number() %% 3==1)
dic_crm <- dic_crm %>%
  select("Sample Name","Area (net avg)","Start Time")
}

#change the net average column to numeric values (from characters)
dic_crm$"Area (net avg)" <- lapply(dic_crm$"Area (net avg)", as.numeric)

if (crm_percent == 5){
  dic_crm5 <- dic_crm %>%
  filter(str_detect(dic_crm$"Sample Name","5%$"))}
else if (crm_percent == 10){
  dic_crm5 <- dic_crm %>%
  filter(str_detect(dic_crm$"Sample Name","10%$"))}
else if (crm_percent == 15){
  dic_crm5 <- dic_crm %>%
  filter(str_detect(dic_crm$"Sample Name","15%$"))}
else {
  dic_crm5 <- dic_crm %>%
  filter(str_detect(dic_crm$"Sample Name","25%$"))}

#Assign the dataframe numbers, use arrange() to make sure CRMs are in correct order
dic_crm5 <- dic_crm5 %>%
  arrange(`Start Time`) %>%
  mutate(funID = row_number())

#Use those functions to find the values for each CRM run. Filter for each different CRM run.
slope1 <- slope((unlist(dic_crm5%>%filter(funID<=3)%>%select("Area (net avg)"))),c(1.2,1.5,1.8))  
intercept1 <- intercept((unlist(dic_crm5%>%filter(funID<=3)%>%select("Area (net avg)"))),c(1.2,1.5,1.8))
rsquared1 <- rsquared((unlist(dic_crm5%>%filter(funID<=3)%>%select("Area (net avg)"))),c(1.2,1.5,1.8), slope1,intercept1)
time1 <- dic_crm5[3,3]

slope2 <- slope((unlist(dic_crm5%>%filter(funID>=4)%>%select("Area (net avg)"))),c(1.2,1.5,1.8))  
intercept2 <- intercept((unlist(dic_crm5%>%filter(funID>=4)%>%select("Area (net avg)"))),c(1.2,1.5,1.8))
rsquared2 <- rsquared((unlist(dic_crm5%>%filter(funID>=4)%>%select("Area (net avg)"))),c(1.2,1.5,1.8), slope2,intercept2)
time2 <- dic_crm5[6,3]

#find the difference in the points of interest for later use
dslope <- slope1-slope2
dintercept <- intercept1-intercept2
dtime <- as.numeric(difftime(time2,time1, units="mins"))

#calculate the CRM DIC (umol/L)
crm_density <- (999.842594 + 0.06793952*roomtemp - 0.00909529*roomtemp^2 + 0.0001001685*roomtemp^3 -0.000001120083*roomtemp^4 +
0.000000006536332*roomtemp^5 + (0.824493-0.0040899*roomtemp + 0.000076438*roomtemp^2 - 0.00000082467*roomtemp^3 +
0.0000000053875*roomtemp^4)*crm_salinity + (-0.00572466 + 0.00010227*roomtemp - 0.0000016546*roomtemp^2)*crm_salinity^1.5 +
0.00048314*crm_salinity^2)/1000
crm_dic <- crm_dic*crm_density

#make sure the values we care about are numeric so they can be used for later calculations
dic_raw$"Area (net)" <- as.numeric(dic_raw$"Area (net)")
dic_raw$"Volume (ml)" <- as.numeric(dic_raw$"Volume (ml)")

#this code is specific to our project and our labeling scheme. Each line is separate because it relies on having the dataframe from the former line.
dic_clean <- dic_raw %>%
  select("Start Time","Sample Name","Volume (ml)","Area (net)") %>%
  filter(!str_detect(`Sample Name`, "junk")) %>%
  filter(!(grepl("CRM", `Sample Name`)))
dic_clean <- dic_clean %>%  
  mutate("CRM Volume (ml)" = (slope1*dic_clean$"Area (net)"+intercept1))
dic_clean <- dic_clean %>%
  mutate(Drift = (slope1+dslope*(as.numeric(difftime(dic_clean$"Start Time",time1, units="mins")))/dtime)*dic_clean$"Area (net)"+(intercept1+dintercept*(as.numeric(difftime(dic_clean$"Start Time",time1, units="mins")))/dtime))
dic_clean <- dic_clean %>%
  mutate("DIC Content (1x10-9 mol)" = (dic_clean$Drift*crm_dic))
dic_clean <- dic_clean %>%
  mutate("DIC (umol/L)" = (dic_clean$"DIC Content (1x10-9 mol)"/dic_clean$"Volume (ml)")) %>%
  mutate("Rm Temp" = roomtemp) %>%
  mutate(Salinity = ifelse(grepl("Sequim", `Sample Name`),3.3,
                      ifelse(grepl("Scott", `Sample Name`),0,
                        ifelse(grepl("B", `Sample Name`), 1.65,
                           ifelse(grepl("S", `Sample Name`), 3.3,
                                         0))))) 
dic_clean <- dic_clean %>%
  mutate("Density (kg/L)" = (999.842594 + 0.06793952*roomtemp - 0.00909529*roomtemp^2 + 0.0001001685*roomtemp^3 -0.000001120083*roomtemp^4 +
0.000000006536332*roomtemp^5 + (0.824493-0.0040899*roomtemp + 0.000076438*roomtemp^2 - 0.00000082467*roomtemp^3 +
0.0000000053875*roomtemp^4)*dic_clean$Salinity + (-0.00572466 + 0.00010227*roomtemp - 0.0000016546*roomtemp^2)*dic_clean$Salinity^1.5 +
0.00048314*dic_clean$Salinity^2)/1000) 
dic_clean <- dic_clean %>%
  mutate("DIC' (umol/kg)" = (dic_clean$"DIC (umol/L)"/dic_clean$"Density (kg/L)"))

return(dic_clean)

}
```

Now we analyze the data...
```{r}
dic_raw_0test <- ditDigest(dic_raw_0, batches = F, crm_percent = 5, roomtemp = 22) # not functional, don't run yet

dic_clean_1 <- ditDigest(dic_raw_1, batches = F, crm_percent = 5, roomtemp = 22)

dic_clean_3 <- ditDigest(dic_raw_3, batches = F, crm_percent = 5, roomtemp = 22)

dic_clean_7 <- ditDigest(dic_raw_7, batches = F, crm_percent = 10, roomtemp = 22)

dic_clean_10 <- ditDigest(dic_raw_10, batches = T, crm_percent = 25, roomtemp = 22)

dic_clean_14 <- ditDigest(dic_raw_14, batches = T, crm_percent = 15, roomtemp = 22)
```
Write to a csv
```{r}
write.csv(dic_clean_1, here("DIC_Raw_Data_Digestion/Data_processed/060424_EBSD_DIT_Day1_DIC_processed.csv"), row.names=FALSE)

write.csv(dic_clean_3, here("DIC_Raw_Data_Digestion/Data_processed/060624_EBSD_DIT_Day3_DIC_processed.csv"), row.names=FALSE)

write.csv(dic_clean_7, here("DIC_Raw_Data_Digestion/Data_processed/061024_EBSD_DIT_Day7_DIC_processed.csv"), row.names=FALSE)

write.csv(dic_clean_10, here("DIC_Raw_Data_Digestion/Data_processed/061324_EBSD_DIT_Day10_DIC_processed.csv"), row.names=FALSE)

write.csv(dic_clean_14, here("DIC_Raw_Data_Digestion/Data_processed/061724_EBSD_DIT_Day14_DIC_processed.csv"), row.names=FALSE)
```